### ISSUE TITLE
Pet rock appears invisible in Firefox 103 on Windows 10

### ISSUE THREAD

**Issue by ThinkerDreamer** [cthulahoops/rocket#20]
https://github.com/cthulahoops/rocket/blob/a3fc2239e1b9333f9ad272d5f05e4fcd4d1e69d5/pets.py#L86
![image](https://user-images.githubusercontent.com/74881094/184911639-2ff23dbb-fd93-4dbb-a848-35ee83508cc0.png)

**Comment by cthulahoops** [comment]
Confirmed this is true on Firefox 103 on Ubuntu too. The rock causes formatting issues in vim too, I'm guessing that it's just too new an emoji. I'm not sure what can be done.

**Comment by cthulahoops** [comment]
The new rock now appears fine for me. Hoping this is no longer an issue.

**Comment by ThinkerDreamer** [comment]
Yeah, it's been working correctly for me for a long time now-- several months at least 👍🏻
